version: 2
defaults: &defaults
  working_directory: ~/gitmoji
  docker:
    - image: circleci/node:12

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn check:typescript
      - run: yarn lint
      - run: |
          yarn build
          node dist/index.js --help
      - persist_to_workspace:
          root: ~/gitmoji
          paths:
            - dist

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/gitmoji
      - run:
          name: 'yarn release'
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/gitmoji/.npmrc
            yarn publish || true

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
